### ISSUE TITLE
time line页面中的文件树怎么打出来的？

### ISSUE THREAD

**Issue by TengHuo** [xinqiu/xinqiu.github.io#1]
[这个页面](http://xinqiu.me/timeline/)
看到你的Blog里有在time line页面中实现了类似于Linux文件树的东西，想知道你是如何在markdown中打出这样的格式的？不胜感激

**Comment by xinqiu** [comment]
说出来你一定会惊讶，其实我只是用了最笨的方法，没错，制表符加上空格。
当然如果你怕麻烦，我倒是想到一个方法，就是在Linux里建个文件夹，里面继续添加文件夹或者文件，名字改为你想要的字，然后用`tree`命令来打印出来，最后在复制一下就可以了。
希望能帮到你。
