### ISSUE TITLE
问下BrowserSync上的客户端连接问题？

### ISSUE THREAD

**Issue by ghost** [xinqiu/xinqiu.github.io#2]
你好，
在[移动端真机调试终极利器-BrowserSync](http://www.codingserf.com/index.php/2015/03/browsersync/#comment-41052)这篇文章中看到了你的评论说你的客户端连接不了网页，我也出现了同样的问题，请问下你的解决没？
我的情况：
  按照上面的教程，我的localhost和PC上的IP地址可以打开页面，但是手机端的一直都连接不上，手机和电脑连在同一个wifi下的，没有代理或VPN，但是尝试好多次都打不开。请问下你的那个问题有方法解决了吗？
我PC是windows系统下，Chrome浏览器，手机Andriod系统下Chrome浏览器，微信二维码也试过，但是无效。
![pc](https://cloud.githubusercontent.com/assets/10086308/8830995/012b7e16-30d2-11e5-8b0f-6bce510d5036.PNG)

**Comment by xinqiu** [comment]
你好，后来我问题解决了。
请问你是在网页目录运行

```
browser-sync start --server --port 4000 --files index.html --files css/main.css
```

这段代码的么？(这里，index.html是首页，main.css放在css目录下)
你上面的截图是什么情况？访问成功的？

**Comment by ghost** [comment]
嗯，截图的意思是在PC端是访问成功了，但是移动端要打开页面还是有问题，不过昨晚折腾了半夜最后能打开了，把browser-sync断开后再重新启动，打开页面后再用手机访问下突然就成功了。。嘿

**Comment by xinqiu** [comment]
对的，我也是的，一开始不成功，后来捣鼓捣鼓就成功了> <
