### ISSUE TITLE
请问这是hexo哪个主题蛮好看的？谢谢～～～  顺便头像换下呗 哈哈

### ISSUE THREAD

**Issue by iStig** [xinqiu/xinqiu.github.io#3]

**Comment by xinqiu** [comment]
是这个主题[tranquilpeak](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak)

为什么我觉得Github自带的头像很好看> <,我会说我大部分社交头像都换成github生成的这个头像了😂

**Comment by iStig** [comment]
thx,你😄就好了～～
